# -*- coding: utf-8 -*-
"""202144021A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FaF0njzULpwmhCayXH6bRhfwmxfavI9p
"""

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

!apt-get -qq -y install fonts-nanum > /dev/null



fe = fm.FontEntry(
    fname=r'/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf',
    name='NanumGothic')
fm.fontManager.ttflist.insert(0, fe)
plt.rcParams.update({'font.size': 18, 'font.family': 'NanumGothic'})

import os
os.kill(os.getpid(), 9)

import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.font_manager as fm


mpl.rcParams['axes.unicode_minus'] = False


fe = fm.FontEntry(
    fname=r'/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf',
    name='NanumGothic')
fm.fontManager.ttflist.insert(0, fe)
plt.rcParams.update({'font.size': 18, 'font.family': 'NanumGothic'})

import requests
import json
import pandas as pd


restaurant_id = "333496"


url = f"https://api.yogiyo.co.kr/reviewyo/legacy/v2/reviews/{restaurant_id}"

params = {
    "count": 30,
    "include_deleted": "false",
    "no_reply_only": "false",
    "only_photo_review": "false",
    "page": 1,
    "sort": "time",
    "sort_order": "desc",
    "type": "all"
}

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36 Edg/142.0.0.0",
    "Authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NjQ5ODgzMjEsImV4cCI6MTc2NDk5NTUyMSwicGxhdGZvcm0iOiJZR1kiLCJyb2xlIjoidXNlciIsInN1Yl9pZCI6IjkxMzQ2NTMzNSIsImJhc2VfdXJsIjoiaHR0cHM6Ly93d3cueW9naXlvLmNvLmtyIn0.oJE-F_wE0AgK_s3K-8NlMN-lgxl4kI6nxUVrwff3w3CXHItCd28sEkM4KQGNUoXefTQ5R-Wt5QxcZQUexq6bdE_ohaEzM5xLmj7DejL0Jq1AFDxXhZGZmOsibKfReQOwwjjXiGIpb-H51OCtQhybsv9VK81sRdupUpTiKBzjZLL3wk7RHInRaRIm_HPIFzVz_gSyUCgSgx8QOw47AYLQWK5tk8kLvPqZAiSiNXKXFQYL62qCdkKRnrXPNEaAVP2Y4RuTBSU7Ay9RqVkPRyPEyksPZS0k8lsBRLCbK-cuydZWuRFGno2LY_1GxhI0G-xxe6GY7t2ob0HPH4OXypGErg",
    "x-apikey": "iphoneap",
    "x-apisecret": "fe5183cc3dea12bd0ce299cf110a75a2",
    "Accept": "application/json"
}

response = requests.get(url, headers=headers, params=params)

if response.status_code != 200:
    print("요청 실패:", response.status_code)
else:
    data = response.json()
    reviews = data
    review_list = []

    for review in reviews:
      review_data = {
        "작성자": review.get("writerName", ""),
        "평점": review.get("rating", ""),
        "내용": review.get("comment", ""),
        "날짜": review.get("createdAt", "")
      }

      review_list.append(review_data)
    df = pd.DataFrame(review_list)
    with open(f"yogiyo_reviews_{restaurant_id}_30.json", "w", encoding="utf-8") as f:
      json.dump(review_list, f, ensure_ascii=False, indent=4)

    print(f"총 {len(review_list)}개 리뷰 수집 완료")


pos_keywords = ['좋아요', '맛있어요', '최고', '가성비', '바삭', '신선']
neg_keywords = ['느림', '짜', '식었어요', '불친절', '맛없']

def sent_score(text):
    pos = sum(word in text for word in pos_keywords)
    neg = sum(word in text for word in neg_keywords)
    if pos > neg:
        return '긍정'
    elif neg > pos:
        return '부정'
    else:
        return '중립'

df['감정'] = df['내용'].apply(sent_score)

print("감정 분석 결과")
print(df[['내용', '감정']], "\n")


print("감정 비율")
print(df['감정'].value_counts(normalize=True) * 100)


import matplotlib.pyplot as plt


sent_ratio = df['감정'].value_counts(normalize=True).reindex(['긍정', '중립', '부정']).fillna(0)


colors = ['green', 'gray', 'red']


plt.figure(figsize=(6,6))
plt.pie(
    sent_ratio.values,
    labels=sent_ratio.index,
    autopct='%.1f%%',
    startangle=90,
    colors=colors,
    wedgeprops={'edgecolor': 'black'}
)

plt.title('요기요 리뷰 감정 비율', fontsize=16, weight='bold')
plt.show()

